spring.application.name=StudentManagement
server.port=${PORT:8080}

# Cấu hình JDBC URL linh hoạt
spring.datasource.url=jdbc:postgresql://ep-cool-tree-aifxz9kg-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_F2unXrWSoQs7
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true