spring.application.name=StudentManagement
# Đổi Driver và URL (Cổng 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=abc123
spring.datasource.driver-class-name=org.postgresql.Driver

# Đổi Dialect cho Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tự động tạo bảng (Rất hữu ích cho bài Lab)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. CẤU HÌNH THYMELEAF
spring.thymeleaf.cache=false